"""crear tablas

Revision ID: 3933209b1d19
Revises: 72910bcb529f
Create Date: 2026-08-13 15:02:33.491958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3933209b1d19'
down_revision = '72910bcb529f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomarcador',
    sa.Column('idBiomarcador', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.Column('idPaciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPaciente'], ['paciente.idPaciente'], ),
    sa.PrimaryKeyConstraint('idBiomarcador')
    )
    op.create_table('toma',
    sa.Column('idToma', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('dosis', sa.String(length=100), nullable=False),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('idMedicamento', sa.Integer(), nullable=False),
    sa.Column('idPaciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idMedicamento'], ['medicamento.idMedicamento'], ),
    sa.ForeignKeyConstraint(['idPaciente'], ['paciente.idPaciente'], ),
    sa.PrimaryKeyConstraint('idToma')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toma')
    op.drop_table('biomarcador')
    # ### end Alembic commands ###
