"""Creación de tablas iniciales

Revision ID: 72910bcb529f
Revises: 
Create Date: 2026-06-28 15:31:48.092336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72910bcb529f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_disponible',
    sa.Column('idStock', sa.Integer(), nullable=False),
    sa.Column('fechaActualizacion', sa.Date(), nullable=False),
    sa.Column('cantidadFrascos', sa.Integer(), nullable=False),
    sa.Column('cantidadPastillas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idStock')
    )
    op.create_table('tipo_alerta',
    sa.Column('idTipoAlerta', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idTipoAlerta')
    )
    op.create_table('tipo_documento',
    sa.Column('idTipoDocumento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('idTipoDocumento')
    )
    op.create_table('tipo_medicamento',
    sa.Column('idTipoMedicamento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idTipoMedicamento')
    )
    op.create_table('via_administracion',
    sa.Column('idViaAdministracion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idViaAdministracion')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fechaNacimiento', sa.Date(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('idTipoDocumento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idTipoDocumento'], ['tipo_documento.idTipoDocumento'], ),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('administrador',
    sa.Column('idAdministrador', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idAdministrador')
    )
    op.create_table('cuidador',
    sa.Column('idCuidador', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idCuidador')
    )
    op.create_table('paciente',
    sa.Column('idPaciente', sa.Integer(), nullable=False),
    sa.Column('estatura', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('tipoSangre', sa.Enum('A_POSITIVO', 'A_NEGATIVO', 'B_POSITIVO', 'B_NEGATIVO', 'O_POSITIVO', 'O_NEGATIVO', 'AB_POSITIVO', 'AB_NEGATIVO', name='tiposangreenum'), nullable=False),
    sa.Column('dieta', sa.String(length=150), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idPaciente')
    )
    op.create_table('adherencia',
    sa.Column('idAdherencia', sa.Integer(), nullable=False),
    sa.Column('fechaGeneracion', sa.Date(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('idPaciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPaciente'], ['paciente.idPaciente'], ),
    sa.PrimaryKeyConstraint('idAdherencia')
    )
    op.create_table('alerta',
    sa.Column('idAlerta', sa.Integer(), nullable=False),
    sa.Column('fechaAlerta', sa.Date(), nullable=False),
    sa.Column('idPaciente', sa.Integer(), nullable=False),
    sa.Column('idTipoAlerta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPaciente'], ['paciente.idPaciente'], ),
    sa.ForeignKeyConstraint(['idTipoAlerta'], ['tipo_alerta.idTipoAlerta'], ),
    sa.PrimaryKeyConstraint('idAlerta')
    )
    op.create_table('tratamiento',
    sa.Column('idTratamiento', sa.Integer(), nullable=False),
    sa.Column('fechaInicio', sa.Date(), nullable=False),
    sa.Column('fechaFin', sa.Date(), nullable=False),
    sa.Column('idPaciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPaciente'], ['paciente.idPaciente'], ),
    sa.PrimaryKeyConstraint('idTratamiento')
    )
    op.create_table('medicamento',
    sa.Column('idMedicamento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('concentracion', sa.Float(), nullable=False),
    sa.Column('frecuenciaDiaria', sa.Integer(), nullable=False),
    sa.Column('fechaVencimiento', sa.Date(), nullable=False),
    sa.Column('idTratamiento', sa.Integer(), nullable=False),
    sa.Column('idTipoMedicamento', sa.Integer(), nullable=False),
    sa.Column('idViaAdministracion', sa.Integer(), nullable=False),
    sa.Column('idStock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idStock'], ['stock_disponible.idStock'], ),
    sa.ForeignKeyConstraint(['idTipoMedicamento'], ['tipo_medicamento.idTipoMedicamento'], ),
    sa.ForeignKeyConstraint(['idTratamiento'], ['tratamiento.idTratamiento'], ),
    sa.ForeignKeyConstraint(['idViaAdministracion'], ['via_administracion.idViaAdministracion'], ),
    sa.PrimaryKeyConstraint('idMedicamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicamento')
    op.drop_table('tratamiento')
    op.drop_table('alerta')
    op.drop_table('adherencia')
    op.drop_table('paciente')
    op.drop_table('cuidador')
    op.drop_table('administrador')
    op.drop_table('usuario')
    op.drop_table('via_administracion')
    op.drop_table('tipo_medicamento')
    op.drop_table('tipo_documento')
    op.drop_table('tipo_alerta')
    op.drop_table('stock_disponible')
    # ### end Alembic commands ###
